# Generated by Django 2.0.7 on 2018-08-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Data de Início')),
                ('fim', models.DateField(verbose_name='Data de Término')),
                ('tags', models.ManyToManyField(to='tags.tag')),
                ('usuarios', models.ManyToManyField(to='usuarios.usuario')),
            ],
        ),
    ]
