# Generated by Django 2.0.7 on 2018-08-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='inicio',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='periodicidade',
            field=models.CharField(choices=[('M', 'Mensal'), ('S', 'Semanal'), ('D', 'Diario')], default='M', max_length=1),
        ),
    ]
