# Generated by Django 2.0.7 on 2018-08-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_auto_20180818_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='periodicidade',
            field=models.CharField(choices=[('S', 'Semanal'), ('D', 'Diário'), ('M', 'Mensal')], default='M', max_length=1),
        ),
    ]
